# Define regions
region = {
    'E' : 'USA',
    'P' : 'EUR',
    'D' : 'NOE',
    'J' : 'JPN',
    'F' : 'FRA',
    'S' : 'ESP',
    'I' : 'ITA'
}
# Define Publishers (incompleted list)
publishers = {
    'A4' : 'Konami',
    'B2' : 'Bandai',
    '00' : 'Null',
    '01' : 'Nintendo',
    '08' : 'Capcom',
    '13' : 'Electronic Arts',
    '14' : 'Hudson Soft',
    '19' : 'B-AI',
    '20' : 'KSS',
    '22' : 'POW',
    '24' : 'PCM Complete',
    '25' : 'San-X',
    '28' : 'Kemco Japan',
    '29' : 'SETA',
    '30' : 'Viacom',
    '31' : 'Nintendo',
    '32' : 'Bandia',
    '33' : 'Ocean/Acclaim',
    '34' : 'Konami',
    '35' : 'Hector',
    '37' : 'Taito',
    '38' : 'Hudson',
    '39' : 'Banpresto',
    '41' : 'Ubisoft',
    '42' : 'Atlus',
    '44' : 'Malibu',
    '46' : 'Angel',
    '47' : 'Pullet-Proof',
    '49' : 'Irem',
    '50' : 'Absolute',
    '51' : 'Acclaim' ,
    '52' : 'Activision',
    '53' : 'American Sammy',
    '54' : 'Konami',
    '55' : 'Hi Tech Entertainment',
    '56' : 'LJN',
    '57' : 'Matchbox',
    '58' : 'Mattel',
    '59' : 'Milton Bradley',
    '60' : 'Titus',
    '61' : 'Virgin',
    '64' : 'LucasArts',
    '67' : 'Ocean',
    '69' : 'Electronic Arts',
    '70' : 'Infogrames',
    '71' : 'Interplay',
    '72' : 'Broderbund',
    '73' : 'Sculptured',
    '75' : 'SCI',
    '78' : 'THQ',
    '79' : 'Accolade',
    '80' : 'Misawa',
    '83' : 'Lozc',
    '86' : 'Tokuma Shoten I*',
    '87' : 'Tsukuda Ori*',
    '91' : 'Chun Soft',
    '92' : 'Video System',
    '93' : 'Ocean/Acclaim',
    '95' : 'Varie',
    '96' : 'Yonezawa\'s pal',
    '97' : 'Kaneko',
    '99' : 'Pack in Soft',
    '7U' : 'Ignition Entertainment',
    'FM' : 'Aspyr Media Inc.',
    'BL' : 'MTO Inc',
    '5N' : 'Metro 3D Inc',
    '7J' : 'ZOO Digital Publishing Ltd.',
    '5H' : '3DO Company',
    '8P' : 'SEGA',
    '6L' : 'BAM! Entertainment',
    'EB' : 'TAKARA',
    '7D' : 'Vivendi Games',
    '7V' : 'Summisoft Corporation',
    '5G' : 'HUDSON SOFT',
    '7F' : 'FIRST STAR SOFTWARE',
    '7N' : 'Empire Interactive',
    'E9' : 'Victor Interactive Software'
}